# 異常

當你的程式出現例外情況時就會發生異常（Exception）。例如，當你想要讀取一個文件時，而那個文件卻不存在，怎麼辦？又或者你在程式時不小心把它刪除了，怎麼辦？這些通過使用**異常**來進行處理。

類似地，如果你的程式中出現了一些無效的語句該怎麼辦？Python 將會對此進行處理，**舉起（Raises）**[^1]它的小手來告訴你哪里出現了一個**錯誤（Error）**。

## 錯誤

你可以想象一個簡單的 `print` 函數調用。如果我們把 `print` 誤拼成 `Print` 會怎樣？你會注意到它的首字母是大寫。在這一例子中，Python 會_拋出（Raise）_一個語法錯誤。

```python
>>> Print("Hello World")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Print' is not defined
>>> print("Hello World")
Hello World
```

你會注意到一個 `NameError` 錯誤被拋出，同時 Python 還會列印出檢測到的錯誤發生的位置。這就是一個錯誤**錯誤處理器（Error Handler）**[^2] 為這個錯誤所做的事情。

## 異常

我們將**嘗試（Try）**去讀取用戶的輸入內容。按下 `[ctrl-d]` 來看看會發生什麼事情。

```python
>>> s = input('Enter something --> ')
Enter something --> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
EOFError
```

此處 Python 指出了一個稱作 `EOFError` 的錯誤，代表著它發現了一個*文件結尾（End of File）*符號（由 `ctrl-d` 實現）在不該出現的時候出現了。

## 處理異常

我們可以通過使用 `try..except` 來處理異常狀況。一般來說我們會把通常的語句放在 try 代碼塊中，將我們的錯誤處理器代碼放置在 except 代碼塊中。

案例（保存文 `exceptions_handle.py`）：

<pre><code class="lang-python">{% include "./programs/exceptions_handle.py" %}</code></pre>

輸出：

<pre><code>{% include "./programs/exceptions_handle.txt" %}</code></pre>

**它是如何工作的**

我們將所有可能引發異常或錯誤的語句放在 `try` 代碼塊中，並將相應的錯誤或異常的處理器（Handler）放在 `except` 子句或代碼塊中。`except` 子句可以處理某種特定的錯誤或異常，或者是一個在括弧中列出的錯誤或異常。如果沒有提供錯誤或異常的名稱，它將處理_所有_錯誤與異常。

要注意到必須至少有一句 `except` 字句與每一句 `try` 字句相關聯。不然，有一個 try 代碼塊又有什麼意義？

如果沒有任何錯誤或異常被處理，那麼將調用 Python 默認處理器，它只會終端程式執行並列印出錯誤資訊。我們已經在前面的章節里見過了這種處理方式。

你還可以擁有一個 `else` 子句與 `try..except` 代碼塊相關聯。`else` 子句將在沒有發生異常的時候執行。

在下一個案例中，我們還將了解如何獲取異常物件以便我們可以檢索其他資訊。

## 拋出異常[^3]

你可以通過 `raise` 語句來_引發_一次異常，具體方法是提供錯誤名或異常名以及要_拋出（Thrown）_異常的物件。

你能夠引發的錯誤或異常必須是直接或間接從屬于 `Exception`（異常） 類的派生類。

案例（保存為 `exceptions_raise.py`）：

<pre><code class="lang-python">{% include "./programs/exceptions_raise.py" %}</code></pre>

輸出：

<pre><code>{% include "./programs/exceptions_raise.txt" %}</code></pre>

**它是如何工作的**

在本例中，我們創建了我們自己的異常類型。這一新的異常類型叫作 `ShortInputException`。它包含兩個欄位——獲取給定輸入文本長度的 `length`，程式期望的最小長度 `atleast`。

在 `except` 子句中，我們提及了錯誤類，將該類存儲 `as（為）` 相應的錯誤名或異常名。這類似于函數調用中的形參與實參。在這個特殊的 `except` 子句中我們使用異常物件的 `length` 與 `atlease` 欄位來向用戶列印一條合適的資訊。

## Try ... Finally {#try-finally}

假設你正在你的讀取中讀取一份文件。你應該如何確保文件物件被正確關閉，無論是否會發生異常？這可以通過 `finally` 塊來完成。

保存該程式為 `exceptions_finally.py`：

<pre><code class="lang-python">{% include "./programs/exceptions_finally.py" %}</code></pre>

輸出：

<pre><code>{% include "./programs/exceptions_finally.txt" %}</code></pre>

**它是如何工作的**

我們按照通常文件讀取進行操作，但是我們同時通過使用 `time.sleep` 函數任意在每列印一行後插入兩秒休眠，使得程式運行變得緩慢（在通常情況下 Python 運行得非常快速）。當程式在處在運行過過程中時，按下 `ctrl + c` 來中斷或取消程式。

你會注意到 `KeyboardInterrupt` 異常被拋出，爾後程式退出。不過，在程式退出之前，finally 子句得到執行，文件物件總會被關閉。

另外要注意到我們在 `print` 之後使用了 `sys.stout.flush()`，以便它能被立即列印到螢幕上。

## `with` 語句 {#with}

在 `try` 塊中獲取資源，然後在 `finally` 塊中釋放資源是一種常見的模式。因此，還有一個 `with` 語句使得這一過程可以以一種幹淨的姿態得以完成。

保存為 `exceptions_using_with.py`：

<pre><code class="lang-python">{% include "./programs/exceptions_using_with.py" %}</code></pre>

**它是如何工作的**

程式輸出的內容應與上一個案例所呈現的相同。本例的不同之處在于我們使用的是 `open` 函數與 `with` 語句——我們將關閉文件的操作交由 `with open` 來自動完成。

在幕後發生的事情是有一項 `with` 語句所使用的協定（Protocol）。它會獲取由 `open` 語句返回的物件，在本案例中就是『thefile』。

它_總會_在代碼塊開始之前調用 `thefile.__enter__` 函數，並且_總會_在代碼塊執行完畢之後調用 `thefile.__exit__`。

因此，我們在 `finally` 代碼塊中編寫的代碼應該格外留心 `__exit__` 方法的自動操作。這能夠幫助我們避免重複發顯式使用 `try..finally` 語句。

有關該話題的更多討論已經超出了本書所能涉及的範圍，因此請參考 [PEP 343](http://www.python.org/dev/peps/pep-0343/) 來了解更加全面的解釋。

## 總結

我們已經討論了 `try..except` 和 `try..finally` 語句的用法。同時我們也已經看到了如何創建我們自己的異常類型，還有如何拋出異常。

接下來，我們將探索 Python 的標准庫。


---

[^1]: 在本章中 Raise 一詞會經常出現，沈潔元譯本大都將其譯作『引發』，此處將按照具體的語境對該詞的譯法作出調整。

[^2]: 此處採用沈潔元譯本的翻譯。但是在其他教程或有關 Python 的討論文章中，Handler 大都保留原文而不作翻譯，這點需讀者知悉。

[^3]: 原文作 Raising Exceptions，沈潔元譯本譯作『引發異常』，此處採用更流行的譯法。